{{- range $value := .Values.components }}
{{- if $value.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $value.persistence.claim_name }}
  labels:
    group: {{ $value.labels.group }}
    product: {{ $value.deployment_name }}
    type: {{ $value.labels.type }}
    version: {{ $value.labels.version }}
    release: {{ $value.labels.product }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $value.persistence.storage_capacity }}
  #storageClassName: {{ $value.persistence.storage_class }}
  volumeMode: Filesystem
{{- end }}
{{- end }}
