image: python:3.12

pipelines:
  branches:
    'development/*':
      - parallel:
          - step:
              name: Test
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - pip install pytest

                - |
                  if [ -d "accounts/tests" ] || [ -d "image/tests" ]; then
                    echo "Tests found, running pytest..."
                    pytest -v accounts/tests/* image/tests/* --junitxml=test-reports/report.xml || true
                  else
                    echo "Warning: No tests found in 'accounts/tests/' or 'image/tests/' directories. Skipping tests."
                  fi
          - step:
              name: Lint code
              script:
                # Enforce style consistency across Python projects https://flake8.pycqa.org
                - pip install flake8
                # Ignores that we use CamalCase for classes, functions, and variables
                - flake8 . --extend-exclude=dist,build --extend-ignore=N802,N803,N806 --show-source --statistics

    # For the `development` Branch
    development:
      - parallel:
          - step:
              name: Test
              caches:
                - pip
              script:
                - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                - pip install pytest

                - |
                  if [ -d "accounts/tests" ] || [ -d "image/tests" ]; then
                    echo "Tests found, running pytest..."
                    pytest -v accounts/tests/* image/tests/* --junitxml=test-reports/report.xml || true
                  else
                    echo "Warning: No tests found in 'accounts/tests/' or 'image/tests/' directories. Skipping tests."
                  fi
          - step:
              name: Lint code
              script:
                # Enforce style consistency across Python projects https://flake8.pycqa.org
                - pip install flake8
                # Ignores that we use CamalCase for classes, functions, and variables
                - flake8 . --extend-exclude=dist,build --extend-ignore=N802,N803,N806 --show-source --statistics