image: python:3.12

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org
            - pip install flake8
            # Ignores that we use CamalCase for classes, functions, and variables
            - flake8 . --extend-exclude=dist,build --extend-ignore=N802,N803,N806 --show-source --statistics
