version: '3.8'

services:
  patholens:
    build: ./patholensProject  # build Backend-Image
    ports:
      - "8000:8000"
    volumes:
      - ./patholensProject:/app  # Mount Code
      - ./media:/app/media  # important for media Nifti files
    environment:
      - PYTHONUNBUFFERED=1
    command: ["sh", "./startup_app.sh"]
