version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    command: ["sh", "./startup_app.sh"]
