# Generated by Django 5.1.3 on 2024-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_diagnosis_confidence_alter_diagnosis_subid'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='editedDiagConfidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
