# Generated by Django 5.1.3 on 2024-12-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_diagnosis_editeddiagconfidence'),
        ('image', '0008_alter_diagnosis_doctor'),
    ]

    operations = [
    ]
